- hosts: all
  vars:
    docker_network: bridge
    ansible_host_key_checking: false ##If you get an error about hosts not trusted
  collections:
    - community.docker
  tasks:
    - name: Remove container
      community.docker.docker_container:
       name: testing_ansible
       state: absent
    
    
    - name: Start container with storage options
      community.docker.docker_container:
        name: testing_ansible
        image: 192.168.2.138:5000/httpd_bks:v1
        ports:
         - "8080:80"
